version: 2.1
jobs:
  say-hello:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "sysctl -a | grep machdep.cpu; brew install colima docker; colima start; docker ps"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
