version: 2.1
jobs:
  say-hello:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "sysctl -a | grep machdep.cpu; brew install docker; brew install colima; colima start; docker run ubuntu:latest"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
